@startuml
start
:创建Component内部静态类Builder;
if (Module里是否全是静态方法) then (是)
else (否)
    if (Module是否是有参构造) then (是)
        :必须自己创建Module实例;
    else (否)
        :可自己创建Module也可不必创建;
    endif
endif
:.build()创建Component实例;
:调用Component接口中的方法;
if(该方法是否有返回类型) then (有)
    :创建该类型（通过该类型工厂类或直接new）;
else (没有)
    :那么该方法是以参数传递进来了实例;
endif
:向该实例注入缺失的对象;
stop
@enduml